USE ELBUENSABOR;

-- SEGUNDA INSERCION


INSERT INTO RUBRO_ARTICULO(ID,DENOMINACION)
VALUES(1,"PIZZAS"),
      (2,"HAMBURGUESAS"),
      (3,"LOMOS"),
      (4,"PAPAS"),
      (5,"BEBIDAS CON ALCOHOL"),
      (6,"BEBIDAS SIN ALCOHOL");