USE ELBUENSABOR;

  -- SEXTA INSERCION
  
INSERT INTO USUARIO(ID,CLAVE,ROL,USUARIO,ID_ROL)
       VALUES(1,"ADMIN","ADMINISTRADOR","ADMIN",1),
			 (2,"COCI","COCINERO","COCI",2),
             (3,"CAJE","CAJERO","CAJE",3),
             (4,"CLI","CLIENTE","CLI",4);